QuickPasteHub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('paste.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

paste/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('paste/create', views.create_paste, name='create_paste'),
    path('pastes', views.ExplorePastes.as_view(), name='explore'),
    path('paste/<str:token>', views.view_paste, name='view_paste'),
    path('paste/<str:token>/edit', views.edit_paste, name='edit_paste'),
]

paste/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.query import QuerySet
from pygments import lexers
import uuid
# Create your models here.


class User(AbstractUser):
    pass


class PrivateManager(models.Manager):
    def get_queryset(self) -> QuerySet:
        return super().get_queryset().filter(private=True)


class PublicManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(private=False)


class Snippet(models.Model):
    languages = [
        (f'{a[0]}', f'{a[0]}') for a in lexers.get_all_lexers()
    ]
    author = models.CharField(max_length=30)
    text = models.TextField()
    private = models.BooleanField(default=False)
    language = models.CharField(
        max_length=53, choices=languages)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    token = models.CharField(max_length=15, unique=True)
    editable = models.BooleanField(default=True)

    objects = models.Manager()
    privates = PrivateManager()
    public = PublicManager()

    def __str__(self):
        return self.author

    def save(self, *args, **kwargs):
        if not self.token:
            self.token = str(uuid.uuid4())[:15]
        return super().save(*args, **kwargs)

paste/forms.py
from django import forms
from .models import Snippet


class SnippetForm(forms.ModelForm):
    class Meta:
        model = Snippet
        fields = ['author', 'text', 'private', 'editable', 'language']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        # Author Field
        self.fields['author'].widget.attrs.update({
            'class': 'input input-bordered input-sm w-full max-w-xs bg-[#0d1117] text-[#c9d1d9] placeholder-[#8b949e] border border-[#30363d] rounded-md',
            'placeholder': 'Author',
        })
        
        # Text Field
        self.fields['text'].widget.attrs.update({
            'class': 'textarea textarea-bordered textarea-sm w-full p-2 bg-[#0d1117] text-[#c9d1d9] placeholder-[#8b949e] border border-[#30363d] rounded-md font-mono',
            'placeholder': 'Write your code or text',
        })
        
        # Private Checkbox
        self.fields['private'].widget.attrs.update({
            'class': 'checkbox checkbox-sm rounded-md border border-[#30363d] bg-[#0d1117] text-[#238636]',
        })
        
        # Editable Checkbox
        self.fields['editable'].widget.attrs.update({
            'class': 'checkbox checkbox-sm rounded-md border border-[#30363d] bg-[#0d1117] text-[#a371f7]',
        })


class SearchForm(forms.Form):
    search = forms.CharField(max_length=15, required=True, widget=forms.TextInput(attrs={
                             'class': 'input input-bordered w-full max-w-xs join-item',
                             'Placeholder': 'search eg. a14477ce-8t7b-4', 'pattern': '[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4'}))

    def clean_search(self):
        search_token = self.cleaned_data['search']
        if len(search_token) < 15:
            raise forms.ValidationError("Invalid token")
        try:
            Snippet.objects.get(token__icontains=search_token)
        except Snippet.DoesNotExist:
            raise forms.ValidationError(
                "Paste with this token does not exist.")
        return search_token

paste/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render, redirect
from django.http import HttpResponseNotFound
from .models import Snippet
from .forms import SnippetForm, SearchForm
from django.views.generic import ListView
# Create your views here.


def index(request):
    if request.GET.get('search', False):
        form = SearchForm(request.GET)
        if form.is_valid():
            search_token = form.cleaned_data['search']
            return redirect('view_paste', token=search_token)
    else:
        form = SearchForm()
    pastes = Snippet.public.all().order_by('-created_at')[:6]
    context = {'pastes': pastes, 'form': form}
    return render(request, 'index.html', context)


def view_paste(request, token):
    if token and len(token) == 15:
        try:
            paste = Snippet.objects.get(token__icontains=token)
            context = {'paste': paste}
        except Snippet.DoesNotExist:
            context = {'error': 'error occured'}
    return render(request, 'view_paste.html', context)


def create_paste(request):
    if request.method == "POST":
        form = SnippetForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('view_paste', form.instance.token)
    else:
        form = SnippetForm()
    previous_url = request.META.get('HTTP_REFERER')
    context = {'form': form, 'previous_url': previous_url}
    return render(request, 'create_paste.html', context)


def edit_paste(request, token):
    try:
        paste = Snippet.objects.get(token=token, editable=True)
    except Snippet.DoesNotExist as e:
        return HttpResponseNotFound()
    if request.method == "POST":
        form = SnippetForm(request.POST, instance=paste)
        if form.is_valid():
            form.save()
            return redirect('view_paste', form.instance.token)
    else:
        form = SnippetForm(instance=paste)
    context = {'form': form, 'edit': True, 'paste': paste}
    return render(request, 'create_paste.html', context)


class ExplorePastes(ListView):
    model = Snippet
    template_name = 'explore_pastes.html'
    context_object_name = 'pastes'
    paginate_by = 8
    ordering = '-modified_at'

    def get_queryset(self) -> QuerySet[Any]:
        return super().get_queryset().filter(private=False)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <title>
        {% block title %}{% endblock title %} - QuickPasteHub</title>
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="title" content="QuickPasteHub">
    <meta name="description"
        content="Welcome to QuickPasteHub, your go-to destination for seamless and rapid content sharing. With QuickPasteHub, users can easily paste and share text, snippets, or any content with a simple click. Whether you're sharing code, notes, or thoughts, our user-friendly platform ensures swift and hassle-free content exchange. Share your ideas, collaborate with others, and streamline communication effortlessly on QuickPasteHub. Start pasting and sharing in an instant!">
    <meta name="keywords" content="text, text share, content share, data,share with friends">
    <meta name="robots" content="index, follow">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="language" content="English">
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'img/site.webmanifest' %}">
    <link rel="mask-icon" href="{% static 'img/safari-pinned-tab.svg' %}" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.15.2/css/selectize.default.min.css"
        integrity="sha512-pTaEn+6gF1IeWv3W1+7X7eM60TFu/agjgoHmYhAfLEU8Phuf6JKiiE8YmsNC0aCgQv4192s4Vai8YZ6VNM6vyQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>

<body class="flex flex-col min-h-screen bg-[#0d1117] text-[#c9d1d9] font-sans">
    <div class="navbar bg-base-200">
        <div class="navbar-start">
            <div class="dropdown">
                <div tabindex="0" role="button" class="btn btn-ghost lg:hidden">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24"
                        stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M4 6h16M4 12h8m-8 6h16" />
                    </svg>
                </div>
                <ul tabindex="0"
                    class="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow bg-base-300 rounded-box w-52">
                    <li class="font-semibold"><a href="{% url 'create_paste' %}">Create</a></li>
                    <li class="font-semibold"><a href="{% url 'explore' %}">Public Pastes</a></li>
                </ul>
            </div>
            <a href="{% url 'home' %}"
                class="btn btn-ghost text-xl bg-clip-text text-transparent antialiased bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 border-none">QuickPasteHub</a>
        </div>
        <div class="navbar-center hidden lg:flex">
            <ul class="menu menu-horizontal px-1">
                <li class="font-semibold"><a href="{% url 'create_paste' %}">Create</a></li>
                <li class="font-semibold"><a href="{% url 'explore' %}">Public Pastes</a></li>
            </ul>
        </div>
    </div>
    <div class="container mx-auto mb-10">
        {% block content %}

        {% endblock content %}
    </div>


    <footer class="footer footer-center p-4 bg-base-200 text-base-content mt-auto">
        <aside>
            {% now "Y" as year %}
            <p>Copyright © {{year}} - All right reserved by QuickPasteHub</p>
            <p class="footer-title">Made with <span class="opacity-100">&#10084;</span> by <a target="_blank"
                    href="https://github.com/e4crypt3d">E4CRYPT3D</a></p>
        </aside>
    </footer>
    <script src="{% static 'js/jquery3.7.1.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.15.2/js/selectize.min.js"
        integrity="sha512-IOebNkvA/HZjMM7MxL0NYeLYEalloZ8ckak+NDtOViP7oiYzG5vn6WVXyrJDiJPhl4yRdmNAG49iuLmhkUdVsQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script>
        $(document).ready(function () {
            $('#id_language').selectize({
                sortField: 'text'
            });
        });</script>
</body>

</html>

templates/create_paste.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Create Paste
{% endblock title %}


{% block content %}


<div class="my-10">
    <div class="my-12">
        <h1
            class="text-3xl font-bold text-center bg-clip-text text-transparent bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 border-none">
            Create a Paste</h1>
    </div>
    <div class="p-6 bg-base-200 rounded-md w-full my-5">
        <div>
            {% if form.non_field_errors %}
            <div role="alert" class="alert alert-error">
                <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none"
                    viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
                <span>{{ form.non_field_errors }}</span>
            </div>
            {% endif %}
        </div>

        {% if edit %}
        <form action="{% url 'edit_paste' paste.token %}" method="post">
            {% else %}
            <form action="{% url 'create_paste' %}" method="post">
                {% endif %}
                {% csrf_token %}
                <label class="form-control w-full max-w-xs">
                    <div class="label">
                        <span class="label-text">{{form.author.label }}</span>
                    </div>
                    {{form.author}}
                    <ul class="mx-8">
                        {% for error in form.author.errors %}
                        <li class="label-text-alt text-error list-disc">{{error}}</li>
                        {% endfor %}
                    </ul>
                </label>
                <label class="block">
                    <!-- Label -->
                    <div class="label">
                        <span class="label-text text-[#c9d1d9] text-sm font-medium">{{ form.text.label }}</span>
                    </div>
                    <!-- Textarea -->
                    <div class="mt-1">
                        {{ form.text }}
                    </div>
                    <!-- Error Messages -->
                    {% if form.text.errors %}
                    <ul class="mt-2 space-y-1">
                        {% for error in form.text.errors %}
                        <li class="text-[#f85149] text-xs font-medium flex items-center gap-1">
                            <svg class="w-3 h-3 fill-current" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg">
                                <path
                                    d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0zm0 11a1 1 0 0 1-1-1V6a1 1 0 0 1 2 0v4a1 1 0 0 1-1 1zm0 2a1 1 0 1 1 0-2 1 1 0 0 1 0 2z">
                                </path>
                            </svg>
                            {{ error }}
                        </li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </label>
                <style>
                    .selectize-control.single .selectize-input.input-active,
                    .selectize-input {
                        background-color: transparent !important;
                    }

                    .selectize-dropdown {
                        background: #eae4cb;
                    }

                    .selectize-control.single .selectize-input {
                        background-image: none;
                        background-color: transparent !important;
                    }
                </style>
                <label class="form-control w-full max-w-xs">
                    <div class="label">
                        <span class="label-text">{{form.language.label}}</span>
                    </div>
                    {{form.language}}
                    <ul class="mx-8">
                        {% for error in form.language.errors %}
                        <li class="label-text-alt text-error list-disc">{{error}}</li>
                        {% endfor %}
                    </ul>
                </label>
                <!-- temp select to be remove -->
                <select class="hidden select select-bordered"></select>
                <div class="form-control max-w-xs">
                    <label class="label cursor-pointer">
                        <span class="label-text">{{form.private.label}}</span>
                        {{form.private}}
                    </label>
                    <ul class="mx-8">
                        {% for error in form.private.errors %}
                        <li class="label-text-alt text-error list-disc">{{error}}</li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="form-control max-w-xs">
                    <label class="label cursor-pointer">
                        <span class="label-text">{{form.editable.label}}</span>
                        {{form.editable}}
                    </label>
                    <ul class="mx-8">

                        {% for error in form.editable.errors %}
                        <li class="label-text-alt text-error list-disc">{{error}}</li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="join flex justify-center mt-6">
                    <!-- Save Button -->
                    <button
                        class="btn join-item bg-[#238636] text-[#ffffff] border border-[#1f6f2e] hover:bg-[#1f6f2e] transition-colors duration-200 py-2 px-4 rounded-md text-sm font-medium"
                        type="submit">
                        Save
                    </button>
                    <!-- Back Button -->
                    <a href="{{ request.META.HTTP_REFERER }}"
                        class="btn join-item bg-[#6b6b6b38] text-[#c9d1d9] border border-[#30363d] hover:bg-[#6b6b6b59] transition-colors duration-200 py-2 px-4 rounded-md text-sm font-medium ml-2">
                        Back
                    </a>
                </div>
            </form>
    </div>
</div>
{% endblock content %}

templates/explore_pastes.html
{% extends 'base.html' %}
{% load static %}
{% load highlight %}

{% block title %}
Explore Pastes
{% endblock title %}



{% block content %}
<div class="my-8">
    <h3
        class="btn w-full my-6 btn-ghost cursor-default font-bold text-center text-xl bg-clip-text text-transparent antialiased bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 border-none">
        Explore Public Pastes</h3>
    <div class="md:grid grid-cols-1 md:grid-cols-2 gap-10">
        {% for paste in pastes  %}
        <div class="card bg-[#0d1117] border border-[#30363d] rounded-lg shadow-md p-3 w-full">
            <div class="card-body">
                <!-- Header Section -->
                <div class="flex items-center gap-2 w-full flex-wrap">
                    <!-- Author -->
                    <h2 class="text-[#c9d1d9] font-semibold text-xs sm:text-sm truncate flex-shrink-0">
                        {{ paste.author|title }}
                    </h2>
                    <!-- Language Badge -->
                    <div
                        class="text-[#ffffff] text-xs sm:text-sm border border-[#30363d] px-2 py-0.5 rounded-full flex-shrink-0">
                        {{ paste.language }}
                    </div>
                    <!-- Date Placeholder -->
                    <div class="ml-auto flex items-center gap-2 flex-wrap">
                        <div class="text-[#8b949e] text-xs sm:text-sm flex-shrink-0">
                            {{ paste.created_at|date:"M d, Y" }}
                        </div>
                        <div
                            class="text-[#ffffff] text-xs sm:text-sm px-2 py-0.5 rounded-full bg-[#238636] flex-shrink-0">
                            Public
                        </div>
                        {% if paste.editable %}
                        <div
                            class="text-[#ffffff] text-xs sm:text-sm px-2 py-0.5 rounded-full bg-[#a371f7] flex-shrink-0">
                            Editable
                        </div>
                        {% endif %}
                    </div>
                </div>
                <!-- Content Section -->
                <div
                    class="mt-3 text-[#c9d1d9] text-xs sm:text-sm font-mono bg-[#161b22] rounded-lg p-3 overflow-auto max-h-36 sm:max-h-48">
                    <span class="hidden" id="text{{ paste.id }}">{{ paste.text }}</span>
                    <pre>{{ paste.text|highlight:paste.language|truncatewords_html:50|safe }}</pre>
                </div>
                <!-- Actions Section -->
                <div class="flex justify-end mt-3 gap-2 flex-wrap">
                    <!-- Copy Button -->
                    <button id="copy{{ paste.id }}" onclick="copyText(`{{ paste.id }}`);"
                        class="flex items-center gap-1 text-[#c9d1d9] text-xs sm:text-sm px-2 py-1 rounded-md bg-[#21262d] border border-[#30363d] hover:bg-[#30363d] transition-colors duration-200 flex-shrink-0">
                        <svg class="w-3 h-3 sm:w-4 sm:h-4" viewBox="0 0 16 16" fill="currentColor">
                            <path
                                d="M5.5 3.5A1.5 1.5 0 0 1 7 2h2.879a1.5 1.5 0 0 1 1.06.44l2.122 2.12a1.5 1.5 0 0 1 .439 1.061V10.5A1.5 1.5 0 0 1 12 12H9v-1h3a.5.5 0 0 0 .5-.5V5.621a.5.5 0 0 0-.146-.354L10.293 3.15a.5.5 0 0 0-.354-.146H7a.5.5 0 0 0-.5.5V6H5.5V3.5z" />
                            <path
                                d="M4 6.5a.5.5 0 0 1 .5-.5H6v4.5A1.5 1.5 0 0 0 7.5 12H12v1.5a1.5 1.5 0 0 1-1.5 1.5H4a1.5 1.5 0 0 1-1.5-1.5v-9A1.5 1.5 0 0 1 4 6.5zm0 9a.5.5 0 0 0 .5.5h6a.5.5 0 0 0 .5-.5V12H4v3.5z" />
                        </svg>
                        Copy
                    </button>
                    <!-- View Button -->
                    <a href="{% url 'view_paste' paste.token %}"
                        class="text-[#c9d1d9] text-xs sm:text-sm px-2 py-1 rounded-md bg-[#21262d] border border-[#30363d] hover:bg-[#30363d] transition-colors duration-200 flex-shrink-0">
                        View
                    </a>
                </div>
            </div>
        </div>
        {% endfor %}

    </div>
    <div class="flex flex-col w-full mt-8 items-center">
        <div class="join">
            {% if page_obj.has_previous %}
            <a href="?page=1" class="join-item btn btn-sm">First</a>
            <a href="?page={{ page_obj.previous_page_number }}"
                class="join-item btn btn-sm">{{ page_obj.previous_page_number }}</a>
            {% endif %}
            <button class="join-item btn btn-sm btn-disabled">{{ page_obj.number }}</button>
            {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}"
                class="join-item btn btn-sm">{{ page_obj.next_page_number }}</a>
            <a href="?page={{ page_obj.paginator.num_pages }}" class="join-item btn btn-sm">Last</a>
            {% endif %}
        </div>
        <span class="text-xs font-semibold p-1">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </span>
    </div>
</div>
<script>
    const copyText = (id) => {
        try {
            // Construct IDs for the text and button elements
            const textId = `text${id}`;
            const copyId = `copy${id}`;

            // Get the text to copy and the button element
            const textElement = document.getElementById(textId);
            const copyButton = document.getElementById(copyId);

            if (!textElement || !copyButton) {
                console.error("Element not found:", { textId, copyId });
                return;
            }

            // Extract the text content to copy
            const pasteText = textElement.textContent.trim();
            if (!pasteText) {
                console.error("No text available to copy.");
                return;
            }

            // Copy the text to the clipboard
            navigator.clipboard.writeText(pasteText).then(() => {
                // Update the button text to indicate success
                copyButton.textContent = "Copied";
                copyButton.classList.add("copied"); // Add a class for styling

                // Revert the button text after 3 seconds
                setTimeout(() => {
                    copyButton.textContent = "Copy";
                    copyButton.classList.remove("copied"); // Remove the class
                }, 3000);
            }).catch((err) => {
                console.error("Failed to copy text:", err);
                alert("Unable to copy text. Please try again.");
            });
        } catch (error) {
            console.error("An error occurred while copying text:", error);
        }
    };
</script>
{% endblock content %}